### ISSUE TITLE
pgcli connection causes pgwire to return an internal error `Unknown type: 0`

### ISSUE THREAD

**Issue by samuelcolvin** [sunng87/pgwire#152]
I'm trying to connect to a server running with pgwire using [pgcli](https://www.pgcli.com/), unfortunately one of the queries pgcli sends after connection is causing an pgwire to return an error, causing an exception in pgcli.

printing the `message` in `ExtendedQueryHandler::on_parse` shows that pgcli is sending the following message:

```
[src/main.rs:122] &message = Parse {
    name: None,
    query: "\n        SELECT  n.nspname schema_name,\n                c.relname table_name\n        FROM    pg_catalog.pg_class c\n                LEFT JOIN pg_catalog.pg_namespace n\n                    ON n.oid = c.relnamespace\n        WHERE   c.relkind = ANY($1)\n        ORDER BY 1,2;",
    type_oids: [
        0,
    ],
}
```

Which in turn is causing an error at 

https://github.com/sunng87/pgwire/blob/f32563b5df5e68bc8701a071228d2c5d19ce94a2/src/api/stmt.rs#L31

since `Type::from_oid` return `None` when the `oid` is `0`.

I don't really understand why `pgcli` is sending an `oid` of zero, but (at the risk of being somewhat simplistic about this?), I would guess either:
* pgcli is doing something invalid (unlikely since it's widely used and connects to most postgres servers fine), then pgwire should return a "client error"
* or, pgcli is doing something reasonable in which case pgwire shouldn't return a `PgWireError`

Am is missing something?

pgcli output:

```
> pgcli 'postgresql://me:pencil@127.0.0.1:54321/foobar'
Server: PostgreSQL 0.19.1
Version: 3.5.0
Home: http://pgcli.com
Exception in thread completion_refresh:
Traceback (most recent call last):
  File "/Users/samuel/.pyenv/versions/3.10.13/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
me@127:foobar>     self.run()
  File "/Users/samuel/.pyenv/versions/3.10.13/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/samuel/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pgcli/completion_refresher.py", line 68, in _bg_refresh
    refresher(completer, executor)
  File "/Users/samuel/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pgcli/completion_refresher.py", line 115, in refresh_tables
    completer.extend_relations(executor.tables(), kind="tables")
  File "/Users/samuel/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pgcli/pgcompleter.py", line 192, in extend_relations
    data = [self.escaped_names(d) for d in data]
  File "/Users/samuel/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pgcli/pgcompleter.py", line 192, in <listcomp>
    data = [self.escaped_names(d) for d in data]
  File "/Users/samuel/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pgcli/pgexecute.py", line 520, in tables
    yield from self._relations(kinds=["r", "p", "f"])
  File "/Users/samuel/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pgcli/pgexecute.py", line 515, in _relations
    cur.execute(self.tables_query, [kinds])
  File "/Users/samuel/.pyenv/versions/3.10.13/lib/python3.10/site-packages/pgcli/pgexecute.py", line 69, in execute
                   super().execute(*args, **kwargs)
  File "/Users/samuel/.pyenv/versions/3.10.13/lib/python3.10/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.OperationalError: consuming input failed: Unknown type: 0
server closed the connection unexpectedlye: OFF  [F4] Emacs-mode  [F5] Explain: OFF      Refreshing completions...             
	This probably means the server terminated abnormally
	before or while processing the request.
```

### MRE code (adapted from the `server.rs` example, but extend to add `ExtendedQueryHandler`

<details>
<summary>See here</summary>

```rs
use std::fmt::Debug;
use std::sync::Arc;

use async_trait::async_trait;
use futures::{stream, Sink, SinkExt, StreamExt};
use tokio::net::TcpListener;

use pgwire::api::auth::noop::NoopStartupHandler;
use pgwire::api::query::{ExtendedQueryHandler, SimpleQueryHandler, StatementOrPortal};
use pgwire::api::results::{DataRowEncoder, DescribeResponse, QueryResponse, Response, Tag};
use pgwire::api::{ClientInfo, ClientPortalStore, MakeHandler, StatelessMakeHandler};
use pgwire::api::portal::Portal;
use pgwire::api::stmt::NoopQueryParser;
use pgwire::api::store::PortalStore;
use pgwire::error::ErrorInfo;
use pgwire::error::{PgWireError, PgWireResult};
use pgwire::messages::extendedquery::Parse;
use pgwire::messages::response::NoticeResponse;
use pgwire::messages::PgWireBackendMessage;
use pgwire::tokio::process_socket;

pub struct DummyProcessor;

#[async_trait]
impl SimpleQueryHandler for DummyProcessor {
    async fn do_query<'a, C>(
        &self,
        client: &mut C,
        query: &'a str,
    ) -> PgWireResult<Vec<Response<'a>>>
    where
        C: ClientInfo + Sink<PgWireBackendMessage> + Unpin + Send + Sync,
        C::Error: Debug,
        PgWireError: From<<C as Sink<PgWireBackendMessage>>::Error>,
    {
        dbg!(query);
        client
            .send(PgWireBackendMessage::NoticeResponse(NoticeResponse::from(
                ErrorInfo::new(
                    "NOTICE".to_owned(),
                    "01000".to_owned(),
                    format!("Query received {}", query),
                ),
            )))
            .await?;

        if query.trim().starts_with("SELECT") {
            let schema = Arc::new(vec![]);

            let data: Vec<Option<i32>> = vec![];
            let schema_ref = schema.clone();
            let data_row_stream = stream::iter(data.into_iter()).map(move |_| {
                DataRowEncoder::new(schema_ref.clone()).finish()
            });

            Ok(vec![Response::Query(QueryResponse::new(
                schema,
                data_row_stream,
            ))])
        } else {
            Ok(vec![Response::Execution(Tag::new("OK").with_rows(1))])
        }
    }
}

#[async_trait]
impl ExtendedQueryHandler for DummyProcessor {
    type Statement = String;
    type QueryParser = NoopQueryParser;

    fn query_parser(&self) -> Arc<Self::QueryParser> {
        let query_parser = NoopQueryParser::new();
        Arc::new(query_parser)
    }

    async fn do_describe<C>(
        &self,
        _client: &mut C,
        target: StatementOrPortal<'_, Self::Statement>,
    ) -> PgWireResult<DescribeResponse>
    where
        C: ClientInfo + Unpin + Send + Sync,
    {
        dbg!(&target);
        Ok(DescribeResponse::new(None, vec![]))
    }

    async fn do_query<'a, C>(
        &self,
        _client: &mut C,
        portal: &'a Portal<Self::Statement>,
        _max_rows: usize,
    ) -> PgWireResult<Response<'a>>
    where
        C: ClientInfo + Unpin + Send + Sync,
    {
        let query = &portal.statement.statement;
        dbg!(query);

        if query.trim().starts_with("SELECT") {
            let schema = Arc::new(vec![]);

            let data: Vec<Option<i32>> = vec![];
            let schema_ref = schema.clone();
            let data_row_stream = stream::iter(data.into_iter()).map(move |_| {
                DataRowEncoder::new(schema_ref.clone()).finish()
            });

            Ok(Response::Query(QueryResponse::new(schema, data_row_stream)))
        } else {
            Ok(Response::Execution(Tag::new("OK").with_rows(1)))
        }
    }

    /// Use this to see what pgcli sends
    // async fn on_parse<C>(&self, _client: &mut C, message: Parse) -> PgWireResult<()>
    // where
    //     C: ClientInfo + ClientPortalStore + Sink<PgWireBackendMessage> + Unpin + Send + Sync,
    //     C::PortalStore: PortalStore<Statement = Self::Statement>,
    //     C::Error: Debug,
    //     PgWireError: From<<C as Sink<PgWireBackendMessage>>::Error>,
    // {
    //     dbg!(&message);
    //     unimplemented!("on_parse")
    // }
}

#[tokio::main]
pub async fn main() {
    let processor = Arc::new(StatelessMakeHandler::new(Arc::new(DummyProcessor)));

    let authenticator = Arc::new(StatelessMakeHandler::new(Arc::new(NoopStartupHandler)));

    let server_addr = "127.0.0.1:54320";
    let listener = TcpListener::bind(server_addr).await.unwrap();
    println!("Listening to {}", server_addr);
    loop {
        let incoming_socket = listener.accept().await.unwrap();
        let authenticator_ref = authenticator.make();
        let processor_ref = processor.make();
        tokio::spawn(async move {
            process_socket(
                incoming_socket.0,
                None,
                authenticator_ref,
                processor_ref.clone(),
                processor_ref,
            )
            .await
        });
    }
}
```

</details>

**Comment by sunng87** [comment]
Thank you for reporting. This is the first time I see type oid 0 being sent to server. It seems postgresql will accept type oid as 0 so we don't need to return error here but send the 0 to application.

**Comment by sunng87** [comment]
@samuelcolvin could you please help me to verify if #153 works for your case?

**Comment by samuelcolvin** [comment]
Yup that seems to be working for me.
